name: Auto-merge Dependabot PRs
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Approve and auto-merge Dependabot PRs
        # Only for patch and minor updates, not major versions
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor'
        run: |
          gh pr review --approve "${{ github.event.pull_request.number }}" --repo "${{ github.repository }}"
          gh pr merge --auto --squash "${{ github.event.pull_request.number }}" --repo "${{ github.repository }}" || echo "Auto-merge failed, will retry later"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}